# This file contains values from Cookiecutter

default_context:
  project_name: "general-q"
  project_description: "An easy to use library for general purpose reinforcement learning and experimentation"
  organization: "axiom"
  license: "MIT"
  minimal_python_version: 3.9
  github_name: "khoda81"
  email: "20.mahdikh.0@gmail.com"
  version: "0.1.0"
  line_length: "80"
  create_example_template: "none"
