wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.9.12
    start_time: 1663407993.226274
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 23
      4: 3.9.12
      5: 0.13.3
      8:
      - 2
      - 3
      - 5
